# @req SCI-HELM-003
# @req SCI-HELM-006
# @req SCI-SEC-001
image:
  repository: nginx
  tag: "1.27.5-alpine"
  pullPolicy: IfNotPresent

replicaCount: 1
containerPort: 8080

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

podSecurityContext:
  fsGroup: 101

securityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
