# @req SCI-HELM-005
# @req SCI-HELM-006
{{- if and .Values.database.createSecret (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db" .Release.Name }}
  namespace: {{ include "sdd-navigator.namespace" . }}
  labels:
    {{- include "sdd-navigator.labels" (dict "root" . "component" "api-secret") | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.usernameKey }}: {{ .Values.database.username | quote }}
  {{ .Values.database.passwordKey }}: {{ .Values.database.password | quote }}
{{- end }}
